class SimuladorBancario :
    '''--------------------
    #Atributos
    --------------------'''
    Cedula=0
    Nombres=''
    MesActual=0
   def ConsignarCuentaCorriente(self):
       return self.saldo 
   def CalcularSaldoTotal(self):
       from CUENTACORRIENTE import CUENTACORRIENTE
       from CUENTAAHORROS import CUENTAAHORROS
       from CDT import CDT

   def PasardeAhorrosaCorriente(self):
   
   def DuplicarAhorro (self):
    self.ahorro *=2
    
    def RetirarTodo(self):
        
        
    def ConsultarSaldoCorriente(self):
        return self.saldocorriente
    '''--------------------
    #Asociasiones
    ---------------------'''
   
